In [1]:
from phe import paillier

In [2]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [3]:
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
public_key,private_key=paillier.generate_paillier_keypair()

In [5]:
def decrypted_mul(x,y):
    xi=private_key.decrypt(x)
    yi=private_key.decrypt(y)
    zi=xi*yi
    z=public_key.encrypt(round(zi,5))
    return z

In [6]:
def security_for_mul(X,Y):
    random_num1=3.776
    random_num2=5.895
    random_mul=random_num1*random_num2
    add1=X*random_num2
    add2=Y*random_num1
    add_on=random_mul+add1+add2
    add_on=add_on*(-1)
    X=X+random_num1
    Y=Y+random_num2
    ans=decrypted_mul(X,Y)
    ans=ans+add_on
    return ans

In [7]:
X_train[:3]

array([[-0.06392624, -0.22104246,  0.18965365,  0.0693698 ,  0.56484236,
         1.63579781, -0.6718682 ,  2.39210964,  0.87489457,  0.19259692],
       [-1.88464871,  0.09205514, -1.61923889,  0.47624035,  2.44122172,
         0.43712678,  2.21441152, -0.993593  ,  2.23427922,  2.52992775],
       [ 0.53130739,  0.26536235,  0.37171417, -0.58275866,  0.39046485,
        -0.10322175, -0.36536815, -0.13427916, -0.90684461, -2.43881716]])

In [8]:
enc_X_train=[]
row=0
for i in X_train:
    row_x=[]
    for j in i:
        z=public_key.encrypt(j)
        row_x.append(z)
    print(f"row={row} encrypted")
    row+=1
    enc_X_train.append(row_x)

row=0 encrypted
row=1 encrypted
row=2 encrypted
row=3 encrypted
row=4 encrypted
row=5 encrypted
row=6 encrypted
row=7 encrypted
row=8 encrypted
row=9 encrypted
row=10 encrypted
row=11 encrypted
row=12 encrypted
row=13 encrypted
row=14 encrypted
row=15 encrypted
row=16 encrypted
row=17 encrypted
row=18 encrypted
row=19 encrypted
row=20 encrypted
row=21 encrypted
row=22 encrypted
row=23 encrypted
row=24 encrypted
row=25 encrypted
row=26 encrypted
row=27 encrypted
row=28 encrypted
row=29 encrypted
row=30 encrypted
row=31 encrypted
row=32 encrypted
row=33 encrypted
row=34 encrypted
row=35 encrypted
row=36 encrypted
row=37 encrypted
row=38 encrypted
row=39 encrypted
row=40 encrypted
row=41 encrypted
row=42 encrypted
row=43 encrypted
row=44 encrypted
row=45 encrypted
row=46 encrypted
row=47 encrypted
row=48 encrypted
row=49 encrypted
row=50 encrypted
row=51 encrypted
row=52 encrypted
row=53 encrypted
row=54 encrypted
row=55 encrypted
row=56 encrypted
row=57 encrypted
row=58 encrypted
row=59 

In [9]:
X_train[799]

array([ 1.84815207e+00, -3.13058031e-01,  1.78069642e+00, -7.08594577e-04,
        1.48411603e+00,  3.55613349e-01, -2.76041632e+00,  6.04515326e-01,
       -1.56102804e+00, -1.25040773e+00])

In [10]:
r=enc_X_train[799]
for i in r:
    print(private_key.decrypt(i))

1.8481520660096302
-0.31305803052315434
1.7806964203609406
-0.0007085945766459172
1.484116028535965
0.35561334878566
-2.760416315820616
0.6045153263553668
-1.561028039293678
-1.2504077339697175


In [11]:
y_train[:3]

array([1, 1, 0])

In [13]:
y_train[1]

1

In [16]:
row=0
enc_y_train=[]
for i in y_train:
    p=public_key.encrypt(int(i))
    enc_y_train.append(p)
    print(f"row={row} encrypted")
    row+=1

row=0 encrypted
row=1 encrypted
row=2 encrypted
row=3 encrypted
row=4 encrypted
row=5 encrypted
row=6 encrypted
row=7 encrypted
row=8 encrypted
row=9 encrypted
row=10 encrypted
row=11 encrypted
row=12 encrypted
row=13 encrypted
row=14 encrypted
row=15 encrypted
row=16 encrypted
row=17 encrypted
row=18 encrypted
row=19 encrypted
row=20 encrypted
row=21 encrypted
row=22 encrypted
row=23 encrypted
row=24 encrypted
row=25 encrypted
row=26 encrypted
row=27 encrypted
row=28 encrypted
row=29 encrypted
row=30 encrypted
row=31 encrypted
row=32 encrypted
row=33 encrypted
row=34 encrypted
row=35 encrypted
row=36 encrypted
row=37 encrypted
row=38 encrypted
row=39 encrypted
row=40 encrypted
row=41 encrypted
row=42 encrypted
row=43 encrypted
row=44 encrypted
row=45 encrypted
row=46 encrypted
row=47 encrypted
row=48 encrypted
row=49 encrypted
row=50 encrypted
row=51 encrypted
row=52 encrypted
row=53 encrypted
row=54 encrypted
row=55 encrypted
row=56 encrypted
row=57 encrypted
row=58 encrypted
row=59 

In [17]:
private_key.decrypt(enc_y_train[4])

0

In [18]:
y_train[4]

0

In [19]:
private_key.decrypt(enc_y_train[444])

0

In [20]:
y_train[444]

0

In [21]:
private_key.decrypt(enc_y_train[1])

1

In [22]:
y_train[1]

1

In [23]:
y_train[609]

0

In [24]:
private_key.decrypt(enc_y_train[609])

0

In [25]:
y_train[610]

1

In [26]:
private_key.decrypt(enc_y_train[610])

1

In [27]:
n_samples,n_attributes=X_train.shape
n_samples,n_attributes

(800, 10)

In [28]:
def sigmoid(z):
    z=private_key.decrypt(z)
    z=round(z,6)
    x=1/(1+np.exp(-z))
    x=round(x,6)
    x=public_key.encrypt(x)
    return x

In [29]:
weights=np.zeros(n_attributes)
bias=0
lr=0.01
weights,bias

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 0)

In [30]:
weights_enc=[]
for i in weights:
    p=public_key.encrypt(i)
    weights_enc.append(p)

In [31]:
bias_enc=public_key.encrypt(bias)
bias

0

In [32]:
bias_enc

#### logistic regression first loop:

In [33]:
xi=enc_X_train[0]
yi=enc_y_train[0]

In [34]:
for i in xi:
    print(private_key.decrypt(i))

-0.063926243091769
-0.22104246353705057
0.1896536515158751
0.06936980265806943
0.5648423586001226
1.635797806135815
-0.6718681998852851
2.3921096352739926
0.8748945673729895
0.19259691873130513


In [35]:
private_key.decrypt(yi)

1

In [36]:
lin_op=0
mul_count=0
for i,j in zip(weights_enc,xi):
    p=security_for_mul(i,j)
    lin_op=lin_op+p
    print(f"multiplication {mul_count} done")
    mul_count=+1

multiplication 0 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done
multiplication 1 done


In [38]:
private_key.decrypt(lin_op)

-7.500330850468565e-06

In [39]:
y_pred=sigmoid(lin_op)
private_key.decrypt(y_pred)

0.499998

In [40]:
pre_dw=y_pred-yi
private_key.decrypt(pre_dw)

-0.5000020000000001

In [43]:
dw=[]
for i in xi:
    p=security_for_mul(i,pre_dw)
    dw.append(p)

In [44]:
for i in dw:
    print(private_key.decrypt(i))

0.03196275502598055
0.11052287455091335
-0.09483072368608149
-0.034687434669317105
-0.2824181519477213
-0.8179005151706282
0.3359305903237581
-1.1960587479401803
-0.43744592266377064
-0.09630128392104231


In [45]:
db=y_pred-yi
private_key.decrypt(db)

-0.5000020000000001

In [47]:
# weights=weights-(lr*dw)
# weights

weights_enc2=[]
for i,j in zip(weights,dw):
    p=i-(lr*j)
    weights_enc2.append(p)

In [48]:
for i in weights_enc2:
    print(private_key.decrypt(i))

-0.00031962755025980556
-0.0011052287455091336
0.0009483072368608149
0.0003468743466931711
0.002824181519477213
0.008179005151706283
-0.003359305903237581
0.011960587479401803
0.004374459226637707
0.0009630128392104231


In [49]:
bias_enc=bias_enc-(lr*db)
private_key.decrypt(bias_enc)

0.00500002

In [50]:
weights_enc=weights_enc2
for i in weights_enc:
    print(private_key.decrypt(i))

-0.00031962755025980556
-0.0011052287455091336
0.0009483072368608149
0.0003468743466931711
0.002824181519477213
0.008179005151706283
-0.003359305903237581
0.011960587479401803
0.004374459226637707
0.0009630128392104231
