In [1]:
import numpy as np
import pandas as pd

In [2]:
n=800
ar=np.arange(n)
ar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [5]:
ar2=np.random.shuffle(ar)
ar

array([232, 371, 476, 686,  26, 184,  54, 142, 120, 422, 501, 558, 324,
       509,  44, 754, 671, 100, 664, 675, 179, 276, 197, 608,  91,  39,
       388, 356, 223, 739, 194, 138, 576, 684, 649,  87,  93, 316, 693,
        95, 340, 342, 272, 279, 418, 799, 417, 118, 393, 710, 444, 211,
       268, 185, 320, 369, 176, 123, 298, 755, 499,  43, 589, 450, 344,
       128, 603, 263,   9, 296, 425, 667, 309, 355, 491, 351, 414,  62,
       670, 492,  94, 712, 253, 633, 140, 733, 540, 631, 568, 364, 716,
       174, 415, 641, 695, 632, 533, 370, 210, 635, 283, 590, 168, 546,
       545, 705, 430, 284, 782, 528, 781, 409, 195, 111, 213, 623,  28,
        57, 673, 683, 766, 741,  89, 468, 482, 596, 645,  74, 758, 744,
       154, 259, 321, 642, 408, 760,  20, 531, 495, 401, 453, 426, 161,
         0, 486, 561, 218,  30, 454, 267,  65, 457, 300, 304, 108, 177,
       776, 503, 127, 347, 292, 598,  70, 788, 713, 139, 345, 170, 455,
       756, 647, 506, 634, 242,  34, 196, 225, 498, 217, 481, 72

In [4]:
ar2

In [6]:
np.random.shuffle(ar)

In [7]:
ar

array([615, 655, 171, 570, 495, 407, 262, 520, 291, 264,  95, 589, 154,
         9, 494, 603, 331, 304, 727, 587, 729, 563, 565, 355, 789, 479,
       767, 254, 621,  75, 134, 359, 673, 688, 639, 580, 684,  77, 239,
       337, 187, 180, 610, 411,  82, 553, 185, 465, 422, 197, 713, 167,
       412, 644,  69, 330, 208,  57, 317, 285, 522, 334, 280, 316, 323,
       716,  20, 265, 295, 604, 755, 457, 778, 189, 574, 256, 162, 258,
       562, 300,  85, 781, 158,  40, 286, 674,  27,  81,  11, 531,  96,
       207,  56, 428, 590,  61, 739, 509, 101, 690, 381, 556, 397,  38,
       209, 115, 792,  44,  87, 229,  99, 701, 252, 138, 245, 710, 592,
       173, 303, 593, 588, 277, 746, 113, 772, 435,  32, 249, 525, 339,
       159,  54, 198, 472, 169, 308, 205, 760,  51, 722, 393, 287, 634,
       206, 220, 480, 106, 693, 694, 147, 409,  98, 447, 463, 467, 600,
       750, 503, 194, 664, 740, 253,  41, 336, 462, 751, 550,  46, 682,
       628, 798, 743, 302, 160, 376, 398,  35, 492, 344, 182, 29